version: "1.0"
name: monintoringappcomposer
services:
  monintoringapp:
 #We name the image as pythonmonitoring, the image will be taken from the dockerfile available at the project folder 
    build: . 
    ports:
      - "7575:7575"