#Ansible Playbook to automatically set Minikube
---
- name: Install Minikube with Podman on macOS and Linux
  hosts: all 
  tasks:
    #Step num#1 - Install dependencies on Ubuntu
    - name: Install dependencies on Debian/Ubuntu
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - conntrack
        state: present
      become: yes
      when: ansible_os_family == "Debian" #Only proceed when the system is based on debian

    #Step num#2 - Install podman on Ubuntu
    - name: Install Podman on Debian/Ubuntu
      apt:
        name: podman
        state: present
      become: yes
      when: ansible_os_family == "Debian"

    #Step num#3: Download Minicube on Linux
    - name: Download Minikube binary for Linux
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'
      become: yes
      when: ansible_os_family == "Debian"

    #Step num#4: Start minikube with podman
    - name: Start Minikube with Podman
      command: minikube start --driver=podman
      register: minikube_start
      changed_when: "'Done' in minikube_start.stdout"
      ignore_errors: yes

    #Step num#8: Get minikube status
    - name: Display Minikube start status
      debug:
        var: minikube_start.stdout
