#Playbook made just to testout an ansible deployment in k8s
- name: demo #The name of the playbook
  hosts: all #The hosts that will be part of the playbook
  tasks:
  #1: Starting minikube
    - name: Starting Minikube
      command: minikube start
      register: minikube_start
      changed_when: "'Done' in minikube_start.stdout"
      ignore_errors: yes

  #2. Starting Prometheus
    - name: Starting Prometheus on Minikube
      command: minikube kubectl -- apply -f prometheus.yaml
      args:
        chdir: ../Kubernetes
      
  #3. Starting Grafana
    - name: Starting Grafana on Minikube
      command: minikube kubectl -- apply -f grafana.yaml

    #4. Starting csadvisor
    - name: Starting Cadvisor on the minikube
      command: minikube kubectl -- apply -f grafana.yaml